plugins {
    id 'org.springframework.boot' version '2.7.14'
    id 'io.spring.dependency-management' version '1.1.2'
    id 'java'
    id 'com.github.node-gradle.node' version '3.1.1'
}

group = 'ai.planit'
version = '0.0.1-SNAPSHOT'

java {
    sourceCompatibility = '11'
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    implementation 'io.netty:netty-resolver-dns-native-macos:4.1.68.Final:osx-aarch_64'
    implementation 'com.google.code.gson:gson:2.8.9'

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:2.3.1'
    runtimeOnly 'org.postgresql:postgresql'
    runtimeOnly 'com.vertica.jdbc:vertica-jdbc:11.0.2-0'
    runtimeOnly files('src/main/libs/VerticaDialect.jar')

    implementation 'com.oracle.ojdbc:orai18n:19.3.0.0'
    runtimeOnly 'com.oracle.database.jdbc:ojdbc8'

    implementation "jakarta.xml.bind:jakarta.xml.bind-api:2.3.2"
    implementation "org.glassfish.jaxb:jaxb-runtime:2.3.2"

    implementation 'org.apache.commons:commons-lang3:3.0'
    implementation 'commons-codec:commons-codec:1.13'
    implementation files("src/main/libs/sdk-1.0.0-all.jar")

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

tasks.named('test') {
//    useJUnitPlatform()
    exclude '**/*'
}

// plain jar 생성X
jar {
    enabled = false
}

// Node-Gradle Config
node {
    version = "16.1.0"
    npmVersion = "7.12.1"
    download = true
    distBaseUrl = "https://nodejs.org/dist"
    npmInstallCommand = "install"
    workDir = file("${project.projectDir}/.gradle/nodejs")
    npmWorkDir = file("${project.projectDir}/.gradle/npm")
    nodeProjectDir = file("${project.projectDir}/src/main/webapp")
}

// Frontend Build
task npmBuild(type: NpmTask) {
    args = ["run", "build"]
}

// Frontend 빌드된 결과 이동
task copyWebApp(type: Copy) {
    from "src/main/webapp/build"
    into "src/main/resources/static"
}

// Frontend 빌드된 결과 삭제
task deleteWebApp(type: Delete) {
    delete "src/main/webapp/build"
    followSymlinks = true
}

copyWebApp.dependsOn(npmBuild)
processResources.dependsOn(copyWebApp)
deleteWebApp.dependsOn(processResources)
compileJava.dependsOn(deleteWebApp)
