spring:
  ods:
    datasource:
      hikari:
        driver-class-name: com.vertica.jdbc.Driver
        jdbc-url: jdbc:vertica://172.26.33.19:5433/CDW
        username: emr
        password: emr1127!
  irb:
    datasource:
      hikari:
        driver-class-name: com.vertica.jdbc.Driver
        url: jdbc:vertica://172.26.33.19:5433/CDW
        username: emr
        password: emr1127!
  pid:
    file: /psdEx/pev/boot.pid
server:
  port: 18083
