spring:
  meta:
    datasource:
      hikari:
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://localhost:5432/pev
        username: pev
        password: pev 
  ods:
    datasource:
      hikari:
        driver-class-name: oracle.jdbc.OracleDriver
        jdbc-url: jdbc:oracle:thin:@172.22.101.11:1521/HSSEMRDD
        username: CDWKYK
        password: pltkyk2512f
  irb:
    datasource:
      hikari:
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://localhost:5434/irb
        username: irb
        password: irb
        maximum-pool-size: 5
        connection-timeout: 30000
